### PR TITLE
Patch missing polygon

### PR DESCRIPTION
**Pull request by ibrahim-sall**
VectorData can now load MultiLinestring and MultiPolygons. I will add some more test but, those already written passed. The major problem (department.geojson loading) is now patch so i ask for PR.

### CODE REVIEW

**Comment by ibrahim-sall** [comment]
Wait to merge, still not working with lyon polygon files...

**Comment by ibrahim-sall** [comment]
Last commit is fine to merge, 2.5 3D is not send to the front since it makes all of the objects displayed far away from the camera

**Review by JBOLIVIER — APPROVED** [review]
checked, no issue seen

**Review by HugGesl — APPROVED** [review]
bravo

**Comment by Vpech77** [comment]
geojson polygon files are loaded and well rendered in the window. The problem is fixed. Good job

**Review by Vpech77 — APPROVED** [review]
geojson polygon files are loaded and well rendered in the window. The problem is fixed. Good job

**Review by lin0qlin — APPROVED** [review]
ok

**Pull request merged**
