### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by JBOLIVIER**
merging in main for v0.1.0

### CODE REVIEW

**Comment by JBOLIVIER** [comment]
Merging v1.0.0 in main

**Review by ibrahim-sall — APPROVED** [review]
Check for this warning during build:
`/home/runner/work/cute-gis/cute-gis/src/front/geotiffloader.cpp: In member function ‘void GeoTiffLoader::loadGeoTIFF(const QString&)’:
/home/runner/work/cute-gis/cute-gis/src/front/geotiffloader.cpp:25:19: warning: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   25 |     band->RasterIO(GF_Read, 0, 0, width, height, buffer.data(), width, height, GDT_Byte, 0, 0);`
Otherwise everything is good.

**Review by lin0qlin — APPROVED** [review]
it works, all good!

**Review by HugGesl — APPROVED** [review]
Aucun bug trouvé. Ok  pour moi

**Review by Vpech77 — APPROVED** [review]
all good

**Pull request merged**
