### PR TITLE
PR for v.0.0 of cute-gis

### PR DESCRIPTION
**Pull request by ibrahim-sall**
Release of a beta version with 2D and 3D mode. It's only possible to visualize vector data at the moment.

### CODE REVIEW

**Review by HugGesl — APPROVED** [review]
Ok mais corriger le test wfs avant de relier au datamanagement

**Comment by ibrahim-sall** [comment]
API_WFSTest can't pass but it's not related to main application yet.

**Review by coincoin42 — APPROVED** [review]
good luck

**Review by thomasb907 — APPROVED** [review]
all good

**Pull request merged**
